

spring:
    profiles:
        active: prod
    banner:
        location: classpath:banner.txt
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
            connectionTimeout: 30000
            idleTimeout: 600000
            maxLifetime: 1800000
            password: password
            username: root
        url: jdbc:mysql://localhost:3306/dictionary
    jpa:
        database-platform: org.hibernate.dialect.MySQL5Dialect
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
                format_sql: true
        show-sql: true
#    main:
#        allow-bean-definition-overriding: true
logging:
        pattern:
            console: "%d %-5level %logger : %msg%n"
        level:
            org.springframework: ERROR
            com.sony.sie.loyalty.: DEBUG
            org.springframework.boot.autoconfigure: INFO
            org.springframework.orm.jpa: DEBUG
            org.springframework.transaction: DEBUG
            org.springframework.web: DEBUG
            org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

springdoc:
    swagger-ui:
            path : /docs
    api-docs:
            path : /api-docs
